-- server 210.17.1.100
USE ventaspdv_verificaciones;

CREATE TABLE checklist_verifica_domicilio_app_tb (
  id INT NOT NULL AUTO_INCREMENT,
  cedulaCliente varchar(100) DEFAULT NULL,
  nombreCliente varchar(100) DEFAULT NULL,
  codigoVerificacion varchar(100) DEFAULT NULL,
  direccionDomiciliaria varchar(100) DEFAULT NULL,
  tipoVivienda varchar(100) DEFAULT NULL,
  personaQuienRealizaLaVerificacion varchar(100) DEFAULT NULL,
  residenciaMinimaTresMeses varchar(100) DEFAULT NULL,
  localTerrenoPropio varchar(100) DEFAULT NULL,
  localTerrenoArrendado varchar(100) DEFAULT NULL,
  planillaServicioBasico varchar(300) DEFAULT NULL,
  planillaServicioBasicoImagen varchar(300) DEFAULT NULL,
  seguridadPuertasVentanas varchar(100) DEFAULT NULL,
  muebleriaBasica varchar(100) DEFAULT NULL,
  materialCasa varchar(100) DEFAULT NULL,
  periodicidadActividadesLaborales varchar(100) DEFAULT NULL,
  confirmacionInfoVecinos varchar(100) DEFAULT NULL,
  nombreInfoVecino varchar(100) DEFAULT NULL,
  celularInfoVecino varchar(100) DEFAULT NULL,
  estabilidadLaboraSeisMesesImagen varchar(300) DEFAULT NULL,
  facturasProveedoresUltimosTresMesesImagen varchar(300) DEFAULT NULL,
  fachadaDelNegocioImagen varchar(300) DEFAULT NULL,
  interiorDelNegocioImagen varchar(300) DEFAULT NULL,
  clienteDentroDelNegocioImagen varchar(300) DEFAULT NULL,
  clienteFueraDelNegocioImagen varchar(300) DEFAULT NULL,
  tituloPropiedaGaranteOCodeudorImagen varchar(300) DEFAULT NULL,
  impuestoPredialImagen varchar(300) DEFAULT NULL,
  respaldoIngresosImagen varchar(300) DEFAULT NULL,
  certificadoLaboralImagen varchar(300) DEFAULT NULL,
  interiorDomicilioImagen varchar(300) DEFAULT NULL,
  latitud varchar(100) DEFAULT NULL,
  longitud varchar(100) DEFAULT NULL,
  coordenadas geometry DEFAULT NULL,
  vf_nombre_tienda varchar(100) DEFAULT NULL,
  nombreGestor varchar(100) DEFAULT NULL,
  fechaverificacion varchar(100) DEFAULT NULL,
  PRIMARY KEY(id)
);


CREATE PROCEDURE proc_insert_checklist_verificacion_app (
  IN p_cedulaCliente VARCHAR(100),
  IN p_nombreCliente VARCHAR(100),
  IN p_codigoVerificacion VARCHAR(100),
  IN p_direccionDomiciliaria VARCHAR(100),
  IN p_tipoVivienda VARCHAR(100),
  IN p_personaQuienRealizaLaVerificacion VARCHAR(100),
  IN p_residenciaMinimaTresMeses VARCHAR(100),
  IN p_localTerrenoPropio VARCHAR(100),
  IN p_localTerrenoArrendado VARCHAR(100),
  IN p_planillaServicioBasico VARCHAR(300),
  IN p_planillaServicioBasicoImagen VARCHAR(300),
  IN p_seguridadPuertasVentanas VARCHAR(100),
  IN p_muebleriaBasica VARCHAR(100),
  IN p_materialCasa VARCHAR(100),
  IN p_periodicidadActividadesLaborales VARCHAR(100),
  IN p_confirmacionInfoVecinos VARCHAR(100),
  IN p_nombreInfoVecino VARCHAR(100),
  IN p_celularInfoVecino VARCHAR(100),
  IN p_estabilidadLaboraSeisMesesImagen VARCHAR(300),
  IN p_facturasProveedoresUltimosTresMesesImagen VARCHAR(300),
  IN p_fachadaDelNegocioImagen VARCHAR(300),
  IN p_interiorDelNegocioImagen VARCHAR(300),
  IN p_clienteDentroDelNegocioImagen VARCHAR(300),
  IN p_clienteFueraDelNegocioImagen VARCHAR(300),
  IN p_tituloPropiedaGaranteOCodeudorImagen VARCHAR(300),
  IN p_impuestoPredialImagen VARCHAR(300),
  IN p_respaldoIngresosImagen VARCHAR(300),
  IN p_certificadoLaboralImagen VARCHAR(300),
  IN p_interiorDomicilioImagen VARCHAR(300),
  IN p_latitud VARCHAR(100),
  IN p_longitud VARCHAR(100),
  IN p_vf_nombre_tienda VARCHAR(100),
  IN p_nombreGestor VARCHAR(100)
)
BEGIN
  INSERT INTO checklist_verifica_domicilio_app_tb (
    id,
    cedulaCliente,
    nombreCliente,
    codigoVerificacion,
    direccionDomiciliaria,
    tipoVivienda,
    personaQuienRealizaLaVerificacion,
    residenciaMinimaTresMeses,
    localTerrenoPropio,
    localTerrenoArrendado,
    planillaServicioBasico,
    planillaServicioBasicoImagen,
    seguridadPuertasVentanas,
    muebleriaBasica,
    materialCasa,
    periodicidadActividadesLaborales,
    confirmacionInfoVecinos,
    nombreInfoVecino,
    celularInfoVecino,
    estabilidadLaboraSeisMesesImagen,
    facturasProveedoresUltimosTresMesesImagen,
    fachadaDelNegocioImagen,
    interiorDelNegocioImagen,
    clienteDentroDelNegocioImagen,
    clienteFueraDelNegocioImagen,
    tituloPropiedaGaranteOCodeudorImagen,
    impuestoPredialImagen,
    respaldoIngresosImagen,
    certificadoLaboralImagen,
    interiorDomicilioImagen,
    latitud,
    longitud,
    coordenadas,
    vf_nombre_tienda,
    nombreGestor,
    fechaverificacion
  )
  VALUES (
    null,
    p_cedulaCliente,
    p_nombreCliente,
    p_codigoVerificacion,
    p_direccionDomiciliaria,
    p_tipoVivienda,
    p_personaQuienRealizaLaVerificacion,
    p_residenciaMinimaTresMeses,
    p_localTerrenoPropio,
    p_localTerrenoArrendado,
    p_planillaServicioBasico,
    p_planillaServicioBasicoImagen,
    p_seguridadPuertasVentanas,
    p_muebleriaBasica,
    p_materialCasa,
    p_periodicidadActividadesLaborales,
    p_confirmacionInfoVecinos,
    p_nombreInfoVecino,
    p_celularInfoVecino,
    p_estabilidadLaboraSeisMesesImagen,
    p_facturasProveedoresUltimosTresMesesImagen,
    p_fachadaDelNegocioImagen,
    p_interiorDelNegocioImagen,
    p_clienteDentroDelNegocioImagen,
    p_clienteFueraDelNegocioImagen,
    p_tituloPropiedaGaranteOCodeudorImagen,
    p_impuestoPredialImagen,
    p_respaldoIngresosImagen,
    p_certificadoLaboralImagen,
    p_interiorDomicilioImagen,
    p_latitud,
    p_longitud,
    POINT(p_latitud, p_longitud),
    p_vf_nombre_tienda,
    p_nombreGestor,
    CURRENT_TIMESTAMP()
  );

  UPDATE verificaciones_usuarios_tb_pruebas SET verificado = '1', nombre_gestor=p_nombreGestor, codigo_verificacion=p_codigoVerificacion 
  WHERE vf_cedula_cliente=p_cedulaCliente;
  SELECT * FROM checklist_verifica_domicilio_app_tb WHERE id = LAST_INSERT_ID();

END;